<div class="widget">
    <h1 class="download-icon">Download PDF</h1>
    
    <?php switch ($pagetype) {
    case "coaching": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/coaching.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/coaching.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "competency_profiling": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/competency_profiling.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/competency_profiling.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "employee_relations": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/employee_relations.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/employee_relations.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "individual_performance_management": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/individual_performance_management.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/individual_performance_management.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "interventions": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/interventions.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/interventions.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "invocoms": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/invocoms.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/invocoms.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "leadership_assessments": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/leadership_assessments.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/leadership_assessments.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "leadership_development": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/operations_management_interventions.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/leadership_development.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "leadership_talent": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/leadership_talent.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/leadership_talent.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "operations_review": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/operations_review.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/operations_review.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "professional_services": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/professional_services.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/professional_services.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "supervisory_skills": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/supervisory_skills.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/supervisory_skills.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "talent_management": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/talent_management.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/talent_management.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break;
    case "team_dynamics": ?><div class="sidebar-content-holder"><img src="<?php echo $relpath; ?>img/pdf-thumbs/team_dynamics.jpg" /></div><a class="sidebar-large-link" href="<?php echo $relpath; ?>downloads/pdf/team_dynamics.pdf" target="_blank"><img src="<?php echo $relpath; ?>img/sidebars/icon-large-link.jpg" alt=">" />Download Now</a><?php break; ?>
   
    <?php } ?>
    
</div>